### ISSUE TITLE
For known issues

### ISSUE THREAD

**Issue by alexwachholz** [rreinecke/global-gradient-based-groundwater-model#2]
ran into 
`Imported targets not available for Boost version 106501`
while executing cmake.
turns out most versions of Boost only work with newer cmake versions (updating cmake  fixed the issue)

Boost 1.63 requires CMake 3.7 or newer.
Boost 1.64 requires CMake 3.8 or newer.
Boost 1.65 and 1.65.1 require CMake 3.9.3 or newer.
Boost 1.66 requires CMake 3.11 or newer.
Boost 1.67 requires CMake 3.12 or newer.
Boost 1.68, 1.69 require CMake 3.13 or newer.

https://stackoverflow.com/questions/42123509/cmake-finds-boost-but-the-imported-targets-not-available-for-boost-version

**Comment by rreinecke** [comment]
@daniel-v-k can you check if that is still an issue?
