### ISSUE TITLE
Upgrade of Boost libraries to newest 1.78 Version

### ISSUE THREAD

**Issue by SebAcki** [rreinecke/global-gradient-based-groundwater-model#35]
**Describe the bug:**
Warnings while compiling the code due to #include <boost/progress.hpp> in helpers.hpp:

boost/timer.hpp warning: This header is depreceated. Use faclilities in <boost/timer/timer.hpp> insterad. [-W#pragma-messages] BOOST_HEADER_DEPRECATED( "the facilities in  boost/timer/timer.hpp>"

--> since version 1.53 outdated and with newer versions marked as depreceated. With version 1.72 in timer/progress_display.

Updating to newest Bosst Version 1.78 will eliminate these warnings.

**Comment by rreinecke** [comment]
@SebAcki @daniel-v-k is this fixed now?

**Comment by daniel-v-k** [comment]
COASTGUARD_dev is now on boost 1.80

Might migrate changes to master next week.
