### ISSUE TITLE
googletest master branch changed to main

### ISSUE THREAD

**Issue by SameerWatve** [rreinecke/global-gradient-based-groundwater-model#9]
This is minor issue googletest github repository does not have master branch anymore which causes build failure.

Updating git tag from "master" to "main" in file: https://github.com/rreinecke/global-gradient-based-groundwater-model/blob/master/CMakeLists_GTest.txt  is easy fix.

**Comment by rreinecke** [comment]
@SebAcki this should be fixed now, right?
